spring:
  application:
    name: github-automation

  jackson:
    deserialization:
      fail-on-unknown-properties: false

github:
  api:
    baseurl: https://api.github.com
    token: TOKEN123
  default:
    owner: mastalerzit
    repo: test-repo
